### ISSUE TITLE
Projection support?

### ISSUE THREAD

**Issue by AlexAslan** [a8m/rql#20]
Hi there...Have you considered adding projection for narrowing down the list of fields?

**Comment by a8m** [comment]
Hey @AlexAslan,
I'm not sure I understand your suggestion, can you give an example?

**Comment by AlexAslan** [comment]
@a8m Thanks for the quick reply. A simple case should be to SELECT specific columns in the generated sql query and not all the columns. The "projection" term is borrowed from mongo.

If we take this https://github.com/a8m/rql#simple-example as a reference the generated sql query would be:
`
SELECT * FROM user WHERE name = false ORDER BY name ASC LIMIT 25 OFFSET 0
`

It would be nice to have something like this:
`
{
  "limit": 25,
  "offset": 0,
  "filter": {
    "admin": false
  }
  "sort": ["+name"],
  "projection": ["id", "name"]
}
`
in order to generate this:
`
SELECT id,name FROM user WHERE name = false ORDER BY name ASC LIMIT 25 OFFSET 0
`

**Comment by AlexAslan** [comment]
Nice one ;) Thanks a lot
