### ISSUE TITLE
How to Express Multiple Predicates of the Same Type

### ISSUE THREAD

**Issue by jon-whit** [a8m/rql#23]
@a8m I want to get a filter that returns all object's whose `status != X` AND `status != Y`.

I would expect something like:
```
{"filter":{"status":{"$neq":"X", "$neq":"Y"}}}
```
The RQL parser only takes the second predicate. So it results in:

`status != Y`

How can I express what I'm trying to express in RQL?

**Comment by a8m** [comment]
Hey, I think [this example](https://github.com/a8m/rql/blob/master/rql_test.go#L146-L150) can solve you problem (I just added it btw).

Closing this. Feel free to open if you still have troubles with it.

**Comment by jon-whit** [comment]
@a8m ah I didn't see that example. Thanks for pointing me in the right direction!
