### ISSUE TITLE
Build Query String

### ISSUE THREAD

**Issue by rockmantist** [a8m/rql#9]
on your example:
curl --request POST --data '{"filter": {"name": {"$like": "t%st"}}}' http://localhost:8080/users

how if we want to use GET request using query string ? how is the query string looks like ?

**Comment by a8m** [comment]
If you are using the example from this repo (which assumes the query-string is base64), you can do it this way:
```
curl http://localhost:8080/users\?query\=$(echo '{"filter": {"name": {"$like": "t%st"}}}' | base64)
```
